### PR TITLE
Added maintainability badge

### PR DESCRIPTION
**Pull request by ernesthenry**
I have added a maintainability badge. But my grade is too low. How can i improve it???

### CODE REVIEW

**Comment by Emmanuelaaron** [comment]
I can see you 93% coverage, what do you mean your grade is still low?

**Comment by lytes20** [comment]
@ernesthenry this shows that its @hadijahkyampeire , can you locally configure the git on that computer to your username and email

**Comment by ernesthenry** [comment]
I have correctly configured the git on my local machine.

**Comment by ernesthenry** [comment]
For the grade, I meant my maintainability badge  @Emmanuelaaron

**Comment by ernesthenry** [comment]
ThANKS for your reviews

**Pull request merged**
